name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Decode Firebase SA Key
      run: |
         ls -alh && mkdir env && echo "${{ secrets.FB_SA_KEY }}" | base64 --decode > env/firebase-sa.json

    - name: Build
      run: yarn build

    - name: Set up Docker
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/makara-backend:$GITHUB_SHA .

    - name: Login to Google Container Registry
      env:
        GCP_SA_KEY: ${{ secrets.COMPUTE_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io

    - name: Push to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/makara-backend:$GITHUB_SHA
  
  deploy-to-gcp:
    env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: ssh and deploy
        run: |
          # Start SSH agent
          eval "$(ssh-agent -s)"
          # Add the SSH key stored in SSH_PRIVATE_KEY to the agent
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          # SSH into the VM and pull the latest Docker image
          ssh -o StrictHostKeyChecking=no c010bsy3533@35.247.81.140 "docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/makara-backend:$GITHUB_SHA && docker run -d --name makara-backend -p 80:3000 gcr.io/${{ secrets.GCP_PROJECT_ID }}/makara-backend:$GITHUB_SHA"
